services:
  svelte-app:
    container_name: symphonicsmp-net
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - GOOGLE_KEY=
      - TWITCH_CLIENT_ID=
      - TWITCH_SECRET=
    restart: unless-stopped
